export const languages: Record<string, string> = {
  plaintext: "Plaintext",
  javascript: "JavaScript",
  typescript: "TypeScript",
  jsx: "JSX",
  tsx: "TSX",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  less: "Less",
  python: "Python",
  java: "Java",
  c: "C",
  cpp: "C++",
  rust: "Rust",
  go: "Go",
  php: "PHP",
  markdown: "Markdown",
  json: "JSON",
  sql: "SQL",
  xml: "XML",
  yaml: "YAML",
  shell: "Shell",
  ruby: "Ruby",
};
