import { ThemeBackground } from "./types";

export const CodeMirrorThemeBackGroundGroup: ThemeBackground[] = [
  { theme: "abyss", bg: "#000c18", type: "dark" },
  { theme: "androidstudio", bg: "#282b2e", type: "dark" },
  { theme: "atomone", bg: "#282c34", type: "dark" },
  { theme: "bbedit", bg: "#ffffff", type: "light" },
  { theme: "bespin", bg: "#28211c", type: "dark" },
  { theme: "darcula", bg: "#2b2b2b", type: "dark" },
  { theme: "dracula", bg: "#282a36", type: "dark" },
  { theme: "duotoneDark", bg: "#2a2734", type: "dark" },
  { theme: "duotoneLight", bg: "#faf8f5", type: "light" },
  { theme: "eclipse", bg: "#ffffff", type: "light" },
  { theme: "githubDark", bg: "#0d1117", type: "dark" },
  { theme: "githubLight", bg: "#ffffff", type: "light" },
  { theme: "gruvboxDark", bg: "#282828", type: "dark" },
  { theme: "gruvboxLight", bg: "#fbf1c7", type: "light" },
  { theme: "material", bg: "#263238", type: "dark" },
  { theme: "monokai", bg: "#272822", type: "dark" },
  { theme: "nord", bg: "#2e3440", type: "dark" },
  { theme: "solarizedDark", bg: "#002b36", type: "dark" },
  { theme: "solarizedLight", bg: "#fdf6e3", type: "light" },
  { theme: "sublime", bg: "#2f3740", type: "dark" },
  { theme: "tokyoNight", bg: "#1a1b26", type: "dark" },
  { theme: "tokyoNightDay", bg: "#e1e2e8", type: "light" },
  { theme: "tomorrowNightBlue", bg: "#002451", type: "dark" },
  { theme: "vscodeDark", bg: "#1e1e1e", type: "dark" },
  { theme: "xcodeDark", bg: "#292a30", type: "dark" },
  { theme: "xcodeLight", bg: "#ffffff", type: "light" },
];
